### ISSUE TITLE
Windows gives this protection dialog when opening the installer

### ISSUE THREAD

**Issue by FlorisRX** [bruhov/WinThumbsPreloader#1]
Windows gives the following warning
![windowsprotectedyourpc](https://user-images.githubusercontent.com/21990961/36864764-e7f9e120-1d8d-11e8-84ef-6e3739d8df32.PNG)

**Comment by bruhov** [comment]
Looks like it's a very common problem:
https://www.google.ru/search?q=windows+protected+your+pc+site%3Agithub.com

Microsoft wants me to sign the application with a paid certificate. Just click "Run anyway".
