### ISSUE TITLE
cmd line version?

### ISSUE THREAD

**Issue by Skrell** [bruhov/WinThumbsPreloader#11]
Would be awesome to have a way to run this from a batch script at night periodically.

**Comment by bruhov** [comment]
Hi! This tool can be run in quiet mode, and you can specify the directory to update thumbnails.
I myself have a .bat file executed on system boot:

`start /B "" "C:\Program Files\WinThumbsPreloader\WinThumbsPreloader.exe" -s "W:\Media"`
