### ISSUE TITLE
Using two options at the same time?

### ISSUE THREAD

**Issue by KevanAwesome** [bruhov/WinThumbsPreloader#17]
Is there a way to use both Recursive and Multi-Threaded and the same time?

I tried Thload -rm <Path>. it just misses the options.

**Comment by VL4DST3R** [comment]
i believe you just separate them by space e.g. `WinThumbsPreloader.exe" -r -m "path"

**Comment by KevanAwesome** [comment]
I'll just use the right click menu now since that's working now.
