### ISSUE TITLE
HTTPS сайта

### ISSUE THREAD

**Issue by WINTEX** [bruhov/WinThumbsPreloader#2]
Поковыряйся в сайте, еле на него зашел, Chrome бьет тревогу, ESET бьет тревогу. Это очень сильно отпугивает. А само приложение отменное. Тут 5+. Must have для владельцев NAS.

**Comment by bruhov** [comment]
Спасибо! После обновления SSL сертификата Let’s Encrypt не перезагрузился nginx. Теперь все нормально :)
