### ISSUE TITLE
Anti-virus goes berserk on executable

### ISSUE THREAD

**Issue by Ingvaerr** [bruhov/WinThumbsPreloader#22]
Since today, my anti-virus application will delete the installer, executable and tmp file that is created during install.
Never had this issue before today.
[Log.txt](https://github.com/bruhov/WinThumbsPreloader/files/7354598/Log.txt)

**Comment by bruhov** [comment]
I am assuming you are using Nod32.
It is strange because here it sees no threat in the installer: https://www.virustotal.com/gui/file/16db5cd90561b342ba3a080e29e833ef35ecc6547932485f85b5d89e2b3b1303

**Comment by Ingvaerr** [comment]
Yes, I'm using Nod32 Internet Security.

There's multiple instances where my antivirus deletes the file because of a detection:
1. when I download the installer from Github
2. when I install the software, it deletes a TMP file that is generated
3. once the install is complete, it will eventually delete the executable located in program files.


![1](https://user-images.githubusercontent.com/92595392/137522524-e1aa36c6-392a-4893-8650-36636f049059.jpg)

**Comment by Ingvaerr** [comment]
Hi,

A few days later and an update of the Eset Nod32 software, and the virus detections don't appear anymore when I download or install the software.
So, problem solved i guess.
